name: Playwright Tests

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'
  pull_request:
    branches:
      - main

jobs:
  test:
    defaults:
      run:
        working-directory: ./apps/web
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9.11.0
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: '23.1.0'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm test

      - name: Upload Playwright test results
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-test-results
          path: ./apps/web/test-results
          retention-days: 30
